// Code generated by "go run types_generate.go"; DO NOT EDIT.

package dns

import (
	"net"
	"slices"
	"strconv"
	"strings"
)

// TypeToRR is a map of constructors for each RR type.
var TypeToRR = map[Type]func() RR{
	TypeA:          func() RR { return new(A) },
	TypeAAAA:       func() RR { return new(AAAA) },
	TypeAFSDB:      func() RR { return new(AFSDB) },
	TypeAMTRELAY:   func() RR { return new(AMTRELAY) },
	TypeANY:        func() RR { return new(ANY) },
	TypeAPL:        func() RR { return new(APL) },
	TypeAVC:        func() RR { return new(AVC) },
	TypeCAA:        func() RR { return new(CAA) },
	TypeCDNSKEY:    func() RR { return new(CDNSKEY) },
	TypeCDS:        func() RR { return new(CDS) },
	TypeCERT:       func() RR { return new(CERT) },
	TypeCNAME:      func() RR { return new(CNAME) },
	TypeCSYNC:      func() RR { return new(CSYNC) },
	TypeDHCID:      func() RR { return new(DHCID) },
	TypeDLV:        func() RR { return new(DLV) },
	TypeDNAME:      func() RR { return new(DNAME) },
	TypeDNSKEY:     func() RR { return new(DNSKEY) },
	TypeDS:         func() RR { return new(DS) },
	TypeEID:        func() RR { return new(EID) },
	TypeEUI48:      func() RR { return new(EUI48) },
	TypeEUI64:      func() RR { return new(EUI64) },
	TypeGID:        func() RR { return new(GID) },
	TypeGPOS:       func() RR { return new(GPOS) },
	TypeHINFO:      func() RR { return new(HINFO) },
	TypeHIP:        func() RR { return new(HIP) },
	TypeHTTPS:      func() RR { return new(HTTPS) },
	TypeIPSECKEY:   func() RR { return new(IPSECKEY) },
	TypeISDN:       func() RR { return new(ISDN) },
	TypeKEY:        func() RR { return new(KEY) },
	TypeKX:         func() RR { return new(KX) },
	TypeL32:        func() RR { return new(L32) },
	TypeL64:        func() RR { return new(L64) },
	TypeLOC:        func() RR { return new(LOC) },
	TypeLP:         func() RR { return new(LP) },
	TypeMB:         func() RR { return new(MB) },
	TypeMD:         func() RR { return new(MD) },
	TypeMF:         func() RR { return new(MF) },
	TypeMG:         func() RR { return new(MG) },
	TypeMINFO:      func() RR { return new(MINFO) },
	TypeMR:         func() RR { return new(MR) },
	TypeMX:         func() RR { return new(MX) },
	TypeNAPTR:      func() RR { return new(NAPTR) },
	TypeNID:        func() RR { return new(NID) },
	TypeNIMLOC:     func() RR { return new(NIMLOC) },
	TypeNINFO:      func() RR { return new(NINFO) },
	TypeNS:         func() RR { return new(NS) },
	TypeNSAPPTR:    func() RR { return new(NSAPPTR) },
	TypeNSEC:       func() RR { return new(NSEC) },
	TypeNSEC3:      func() RR { return new(NSEC3) },
	TypeNSEC3PARAM: func() RR { return new(NSEC3PARAM) },
	TypeNULL:       func() RR { return new(NULL) },
	TypeNXNAME:     func() RR { return new(NXNAME) },
	TypeNXT:        func() RR { return new(NXT) },
	TypeOPENPGPKEY: func() RR { return new(OPENPGPKEY) },
	TypeOPT:        func() RR { return new(OPT) },
	TypePTR:        func() RR { return new(PTR) },
	TypePX:         func() RR { return new(PX) },
	TypeRESINFO:    func() RR { return new(RESINFO) },
	TypeRKEY:       func() RR { return new(RKEY) },
	TypeRP:         func() RR { return new(RP) },
	TypeRRSIG:      func() RR { return new(RRSIG) },
	TypeRT:         func() RR { return new(RT) },
	TypeSIG:        func() RR { return new(SIG) },
	TypeSMIMEA:     func() RR { return new(SMIMEA) },
	TypeSOA:        func() RR { return new(SOA) },
	TypeSPF:        func() RR { return new(SPF) },
	TypeSRV:        func() RR { return new(SRV) },
	TypeSSHFP:      func() RR { return new(SSHFP) },
	TypeSVCB:       func() RR { return new(SVCB) },
	TypeTA:         func() RR { return new(TA) },
	TypeTALINK:     func() RR { return new(TALINK) },
	TypeTKEY:       func() RR { return new(TKEY) },
	TypeTLSA:       func() RR { return new(TLSA) },
	TypeTSIG:       func() RR { return new(TSIG) },
	TypeTXT:        func() RR { return new(TXT) },
	TypeUID:        func() RR { return new(UID) },
	TypeUINFO:      func() RR { return new(UINFO) },
	TypeURI:        func() RR { return new(URI) },
	TypeX25:        func() RR { return new(X25) },
	TypeZONEMD:     func() RR { return new(ZONEMD) },
}

// TypeToString is a map of strings for each RR type.
var TypeToString = map[Type]string{
	TypeA:          "A",
	TypeAAAA:       "AAAA",
	TypeAFSDB:      "AFSDB",
	TypeAMTRELAY:   "AMTRELAY",
	TypeANY:        "ANY",
	TypeAPL:        "APL",
	TypeATMA:       "ATMA",
	TypeAVC:        "AVC",
	TypeAXFR:       "AXFR",
	TypeCAA:        "CAA",
	TypeCDNSKEY:    "CDNSKEY",
	TypeCDS:        "CDS",
	TypeCERT:       "CERT",
	TypeCNAME:      "CNAME",
	TypeCSYNC:      "CSYNC",
	TypeDHCID:      "DHCID",
	TypeDLV:        "DLV",
	TypeDNAME:      "DNAME",
	TypeDNSKEY:     "DNSKEY",
	TypeDS:         "DS",
	TypeEID:        "EID",
	TypeEUI48:      "EUI48",
	TypeEUI64:      "EUI64",
	TypeGID:        "GID",
	TypeGPOS:       "GPOS",
	TypeHINFO:      "HINFO",
	TypeHIP:        "HIP",
	TypeHTTPS:      "HTTPS",
	TypeIPSECKEY:   "IPSECKEY",
	TypeISDN:       "ISDN",
	TypeIXFR:       "IXFR",
	TypeKEY:        "KEY",
	TypeKX:         "KX",
	TypeL32:        "L32",
	TypeL64:        "L64",
	TypeLOC:        "LOC",
	TypeLP:         "LP",
	TypeMAILA:      "MAILA",
	TypeMAILB:      "MAILB",
	TypeMB:         "MB",
	TypeMD:         "MD",
	TypeMF:         "MF",
	TypeMG:         "MG",
	TypeMINFO:      "MINFO",
	TypeMR:         "MR",
	TypeMX:         "MX",
	TypeNAPTR:      "NAPTR",
	TypeNID:        "NID",
	TypeNIMLOC:     "NIMLOC",
	TypeNINFO:      "NINFO",
	TypeNS:         "NS",
	TypeNSEC:       "NSEC",
	TypeNSEC3:      "NSEC3",
	TypeNSEC3PARAM: "NSEC3PARAM",
	TypeNULL:       "NULL",
	TypeNXNAME:     "NXNAME",
	TypeNXT:        "NXT",
	TypeNone:       "None",
	TypeOPENPGPKEY: "OPENPGPKEY",
	TypeOPT:        "OPT",
	TypePTR:        "PTR",
	TypePX:         "PX",
	TypeRESINFO:    "RESINFO",
	TypeRKEY:       "RKEY",
	TypeRP:         "RP",
	TypeRRSIG:      "RRSIG",
	TypeRT:         "RT",
	TypeReserved:   "Reserved",
	TypeSIG:        "SIG",
	TypeSMIMEA:     "SMIMEA",
	TypeSOA:        "SOA",
	TypeSPF:        "SPF",
	TypeSRV:        "SRV",
	TypeSSHFP:      "SSHFP",
	TypeSVCB:       "SVCB",
	TypeTA:         "TA",
	TypeTALINK:     "TALINK",
	TypeTKEY:       "TKEY",
	TypeTLSA:       "TLSA",
	TypeTSIG:       "TSIG",
	TypeTXT:        "TXT",
	TypeUID:        "UID",
	TypeUINFO:      "UINFO",
	TypeUNSPEC:     "UNSPEC",
	TypeURI:        "URI",
	TypeX25:        "X25",
	TypeZONEMD:     "ZONEMD",
	TypeNSAPPTR:    "NSAP-PTR",
}

func (rr *A) Header() *RR_Header          { return &rr.Hdr }
func (rr *AAAA) Header() *RR_Header       { return &rr.Hdr }
func (rr *AFSDB) Header() *RR_Header      { return &rr.Hdr }
func (rr *AMTRELAY) Header() *RR_Header   { return &rr.Hdr }
func (rr *ANY) Header() *RR_Header        { return &rr.Hdr }
func (rr *APL) Header() *RR_Header        { return &rr.Hdr }
func (rr *AVC) Header() *RR_Header        { return &rr.Hdr }
func (rr *CAA) Header() *RR_Header        { return &rr.Hdr }
func (rr *CDNSKEY) Header() *RR_Header    { return &rr.Hdr }
func (rr *CDS) Header() *RR_Header        { return &rr.Hdr }
func (rr *CERT) Header() *RR_Header       { return &rr.Hdr }
func (rr *CNAME) Header() *RR_Header      { return &rr.Hdr }
func (rr *CSYNC) Header() *RR_Header      { return &rr.Hdr }
func (rr *DHCID) Header() *RR_Header      { return &rr.Hdr }
func (rr *DLV) Header() *RR_Header        { return &rr.Hdr }
func (rr *DNAME) Header() *RR_Header      { return &rr.Hdr }
func (rr *DNSKEY) Header() *RR_Header     { return &rr.Hdr }
func (rr *DS) Header() *RR_Header         { return &rr.Hdr }
func (rr *EID) Header() *RR_Header        { return &rr.Hdr }
func (rr *EUI48) Header() *RR_Header      { return &rr.Hdr }
func (rr *EUI64) Header() *RR_Header      { return &rr.Hdr }
func (rr *GID) Header() *RR_Header        { return &rr.Hdr }
func (rr *GPOS) Header() *RR_Header       { return &rr.Hdr }
func (rr *HINFO) Header() *RR_Header      { return &rr.Hdr }
func (rr *HIP) Header() *RR_Header        { return &rr.Hdr }
func (rr *HTTPS) Header() *RR_Header      { return &rr.Hdr }
func (rr *IPSECKEY) Header() *RR_Header   { return &rr.Hdr }
func (rr *ISDN) Header() *RR_Header       { return &rr.Hdr }
func (rr *KEY) Header() *RR_Header        { return &rr.Hdr }
func (rr *KX) Header() *RR_Header         { return &rr.Hdr }
func (rr *L32) Header() *RR_Header        { return &rr.Hdr }
func (rr *L64) Header() *RR_Header        { return &rr.Hdr }
func (rr *LOC) Header() *RR_Header        { return &rr.Hdr }
func (rr *LP) Header() *RR_Header         { return &rr.Hdr }
func (rr *MB) Header() *RR_Header         { return &rr.Hdr }
func (rr *MD) Header() *RR_Header         { return &rr.Hdr }
func (rr *MF) Header() *RR_Header         { return &rr.Hdr }
func (rr *MG) Header() *RR_Header         { return &rr.Hdr }
func (rr *MINFO) Header() *RR_Header      { return &rr.Hdr }
func (rr *MR) Header() *RR_Header         { return &rr.Hdr }
func (rr *MX) Header() *RR_Header         { return &rr.Hdr }
func (rr *NAPTR) Header() *RR_Header      { return &rr.Hdr }
func (rr *NID) Header() *RR_Header        { return &rr.Hdr }
func (rr *NIMLOC) Header() *RR_Header     { return &rr.Hdr }
func (rr *NINFO) Header() *RR_Header      { return &rr.Hdr }
func (rr *NS) Header() *RR_Header         { return &rr.Hdr }
func (rr *NSAPPTR) Header() *RR_Header    { return &rr.Hdr }
func (rr *NSEC) Header() *RR_Header       { return &rr.Hdr }
func (rr *NSEC3) Header() *RR_Header      { return &rr.Hdr }
func (rr *NSEC3PARAM) Header() *RR_Header { return &rr.Hdr }
func (rr *NULL) Header() *RR_Header       { return &rr.Hdr }
func (rr *NXNAME) Header() *RR_Header     { return &rr.Hdr }
func (rr *NXT) Header() *RR_Header        { return &rr.Hdr }
func (rr *OPENPGPKEY) Header() *RR_Header { return &rr.Hdr }
func (rr *OPT) Header() *RR_Header        { return &rr.Hdr }
func (rr *PTR) Header() *RR_Header        { return &rr.Hdr }
func (rr *PX) Header() *RR_Header         { return &rr.Hdr }
func (rr *RESINFO) Header() *RR_Header    { return &rr.Hdr }
func (rr *RFC3597) Header() *RR_Header    { return &rr.Hdr }
func (rr *RKEY) Header() *RR_Header       { return &rr.Hdr }
func (rr *RP) Header() *RR_Header         { return &rr.Hdr }
func (rr *RRSIG) Header() *RR_Header      { return &rr.Hdr }
func (rr *RT) Header() *RR_Header         { return &rr.Hdr }
func (rr *SIG) Header() *RR_Header        { return &rr.Hdr }
func (rr *SMIMEA) Header() *RR_Header     { return &rr.Hdr }
func (rr *SOA) Header() *RR_Header        { return &rr.Hdr }
func (rr *SPF) Header() *RR_Header        { return &rr.Hdr }
func (rr *SRV) Header() *RR_Header        { return &rr.Hdr }
func (rr *SSHFP) Header() *RR_Header      { return &rr.Hdr }
func (rr *SVCB) Header() *RR_Header       { return &rr.Hdr }
func (rr *TA) Header() *RR_Header         { return &rr.Hdr }
func (rr *TALINK) Header() *RR_Header     { return &rr.Hdr }
func (rr *TKEY) Header() *RR_Header       { return &rr.Hdr }
func (rr *TLSA) Header() *RR_Header       { return &rr.Hdr }
func (rr *TSIG) Header() *RR_Header       { return &rr.Hdr }
func (rr *TXT) Header() *RR_Header        { return &rr.Hdr }
func (rr *UID) Header() *RR_Header        { return &rr.Hdr }
func (rr *UINFO) Header() *RR_Header      { return &rr.Hdr }
func (rr *URI) Header() *RR_Header        { return &rr.Hdr }
func (rr *X25) Header() *RR_Header        { return &rr.Hdr }
func (rr *ZONEMD) Header() *RR_Header     { return &rr.Hdr }

// len() functions
func (rr *A) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	if rr.A.IsValid() {
		l += net.IPv4len
	}
	return l
}

func (rr *AAAA) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	if rr.AAAA.IsValid() {
		l += net.IPv6len
	}
	return l
}

func (rr *AFSDB) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += 2 // Subtype
	l += domainNameLen(rr.Hostname, off+l, compression, false)
	return l
}

func (rr *AMTRELAY) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l++ // Precedence
	l++ // GatewayType
	switch rr.GatewayType {
	case AMTRELAYIPv4:
		l += net.IPv4len
	case AMTRELAYIPv6:
		l += net.IPv6len
	case AMTRELAYHost:
		l += domainNameLen(rr.GatewayHost, off+l, compression, false)
	}
	return l
}

func (rr *ANY) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	return l
}

func (rr *APL) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	for _, x := range rr.Prefixes {
		l += x.len()
	}
	return l
}

func (rr *AVC) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += rr.Txt.EncodedLen()
	return l
}

func (rr *CAA) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l++ // Flag
	l += rr.Tag.EncodedLen()
	l += escapedNameLen(rr.Value)
	return l
}

func (rr *CERT) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += 2 // Type
	l += 2 // KeyTag
	l++    // Algorithm
	l += rr.Certificate.EncodedLen()
	return l
}

func (rr *CNAME) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += domainNameLen(rr.Target, off+l, compression, true)
	return l
}

func (rr *DHCID) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += rr.Digest.EncodedLen()
	return l
}

func (rr *DNAME) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += domainNameLen(rr.Target, off+l, compression, false)
	return l
}

func (rr *DNSKEY) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += 2 // Flags
	l++    // Protocol
	l++    // Algorithm
	l += rr.PublicKey.EncodedLen()
	return l
}

func (rr *DS) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += 2 // KeyTag
	l++    // Algorithm
	l++    // DigestType
	l += rr.Digest.EncodedLen()
	return l
}

func (rr *EID) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += rr.Endpoint.EncodedLen()
	return l
}

func (rr *EUI48) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += 6 // Address
	return l
}

func (rr *EUI64) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += 8 // Address
	return l
}

func (rr *GID) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += 4 // Gid
	return l
}

func (rr *GPOS) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += rr.Longitude.EncodedLen()
	l += rr.Latitude.EncodedLen()
	l += rr.Altitude.EncodedLen()
	return l
}

func (rr *HINFO) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += rr.Cpu.EncodedLen()
	l += rr.Os.EncodedLen()
	return l
}

func (rr *HIP) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l++    // HitLength
	l++    // PublicKeyAlgorithm
	l += 2 // PublicKeyLength
	l += rr.Hit.EncodedLen()
	l += rr.PublicKey.EncodedLen()
	for _, x := range rr.RendezvousServers {
		l += domainNameLen(x, off+l, compression, false)
	}
	return l
}

func (rr *IPSECKEY) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l++ // Precedence
	l++ // GatewayType
	l++ // Algorithm
	switch rr.GatewayType {
	case IPSECGatewayIPv4:
		l += net.IPv4len
	case IPSECGatewayIPv6:
		l += net.IPv6len
	case IPSECGatewayHost:
		l += domainNameLen(rr.GatewayHost, off+l, compression, false)
	}
	l += rr.PublicKey.EncodedLen()
	return l
}

func (rr *ISDN) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += rr.Address.EncodedLen()
	l += rr.SubAddress.EncodedLen()
	return l
}

func (rr *KX) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += 2 // Preference
	l += domainNameLen(rr.Exchanger, off+l, compression, false)
	return l
}

func (rr *L32) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += 2 // Preference
	if rr.Locator32.IsValid() {
		l += net.IPv4len
	}
	return l
}

func (rr *L64) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += 2 // Preference
	l += 8 // Locator64
	return l
}

func (rr *LOC) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l++    // Version
	l++    // Size
	l++    // HorizPre
	l++    // VertPre
	l += 4 // Latitude
	l += 4 // Longitude
	l += 4 // Altitude
	return l
}

func (rr *LP) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += 2 // Preference
	l += domainNameLen(rr.Fqdn, off+l, compression, false)
	return l
}

func (rr *MB) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += domainNameLen(rr.Mb, off+l, compression, true)
	return l
}

func (rr *MD) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += domainNameLen(rr.Md, off+l, compression, true)
	return l
}

func (rr *MF) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += domainNameLen(rr.Mf, off+l, compression, true)
	return l
}

func (rr *MG) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += domainNameLen(rr.Mg, off+l, compression, true)
	return l
}

func (rr *MINFO) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += domainNameLen(rr.Rmail, off+l, compression, true)
	l += domainNameLen(rr.Email, off+l, compression, true)
	return l
}

func (rr *MR) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += domainNameLen(rr.Mr, off+l, compression, true)
	return l
}

func (rr *MX) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += 2 // Preference
	l += domainNameLen(rr.Mx, off+l, compression, true)
	return l
}

func (rr *NAPTR) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += 2 // Order
	l += 2 // Preference
	l += rr.Flags.EncodedLen()
	l += rr.Service.EncodedLen()
	l += escapedNameLen(rr.Regexp) + 1
	l += domainNameLen(rr.Replacement, off+l, compression, false)
	return l
}

func (rr *NID) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += 2 // Preference
	l += 8 // NodeID
	return l
}

func (rr *NIMLOC) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += rr.Locator.EncodedLen()
	return l
}

func (rr *NINFO) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += rr.ZSData.EncodedLen()
	return l
}

func (rr *NS) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += domainNameLen(rr.Ns, off+l, compression, true)
	return l
}

func (rr *NSAPPTR) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += domainNameLen(rr.Ptr, off+l, compression, false)
	return l
}

func (rr *NSEC3PARAM) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l++    // Hash
	l++    // Flags
	l += 2 // Iterations
	l++    // SaltLength
	l += rr.Salt.EncodedLen()
	return l
}

func (rr *NULL) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += rr.Data.EncodedLen()
	return l
}

func (rr *NXNAME) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	return l
}

func (rr *OPENPGPKEY) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += rr.PublicKey.EncodedLen()
	return l
}

func (rr *PTR) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += domainNameLen(rr.Ptr, off+l, compression, true)
	return l
}

func (rr *PX) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += 2 // Preference
	l += domainNameLen(rr.Map822, off+l, compression, false)
	l += domainNameLen(rr.Mapx400, off+l, compression, false)
	return l
}

func (rr *RESINFO) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += rr.Txt.EncodedLen()
	return l
}

func (rr *RFC3597) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += rr.Rdata.EncodedLen()
	return l
}

func (rr *RKEY) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += 2 // Flags
	l++    // Protocol
	l++    // Algorithm
	l += rr.PublicKey.EncodedLen()
	return l
}

func (rr *RP) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += domainNameLen(rr.Mbox, off+l, compression, false)
	l += domainNameLen(rr.Txt, off+l, compression, false)
	return l
}

func (rr *RRSIG) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += 2 // TypeCovered
	l++    // Algorithm
	l++    // Labels
	l += 4 // OrigTtl
	l += 4 // Expiration
	l += 4 // Inception
	l += 2 // KeyTag
	l += domainNameLen(rr.SignerName, off+l, compression, false)
	l += rr.Signature.EncodedLen()
	return l
}

func (rr *RT) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += 2 // Preference
	l += domainNameLen(rr.Host, off+l, compression, false)
	return l
}

func (rr *SMIMEA) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l++ // Usage
	l++ // Selector
	l++ // MatchingType
	l += rr.Certificate.EncodedLen()
	return l
}

func (rr *SOA) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += domainNameLen(rr.Ns, off+l, compression, true)
	l += domainNameLen(rr.Mbox, off+l, compression, true)
	l += 4 // Serial
	l += 4 // Refresh
	l += 4 // Retry
	l += 4 // Expire
	l += 4 // Minttl
	return l
}

func (rr *SPF) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += rr.Txt.EncodedLen()
	return l
}

func (rr *SRV) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += 2 // Priority
	l += 2 // Weight
	l += 2 // Port
	l += domainNameLen(rr.Target, off+l, compression, false)
	return l
}

func (rr *SSHFP) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l++ // Algorithm
	l++ // Type
	l += rr.FingerPrint.EncodedLen()
	return l
}

func (rr *SVCB) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += 2 // Priority
	l += domainNameLen(rr.Target, off+l, compression, false)
	for _, x := range rr.Value {
		l += 4 + int(x.len())
	}
	return l
}

func (rr *TA) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += 2 // KeyTag
	l++    // Algorithm
	l++    // DigestType
	l += rr.Digest.EncodedLen()
	return l
}

func (rr *TALINK) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += domainNameLen(rr.PreviousName, off+l, compression, false)
	l += domainNameLen(rr.NextName, off+l, compression, false)
	return l
}

func (rr *TKEY) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += domainNameLen(rr.Algorithm, off+l, compression, false)
	l += 4 // Inception
	l += 4 // Expiration
	l += 2 // Mode
	l += 2 // Error
	l += 2 // KeySize
	l += rr.Key.EncodedLen()
	l += 2 // OtherLen
	l += rr.OtherData.EncodedLen()
	return l
}

func (rr *TLSA) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l++ // Usage
	l++ // Selector
	l++ // MatchingType
	l += rr.Certificate.EncodedLen()
	return l
}

func (rr *TSIG) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += domainNameLen(rr.Algorithm, off+l, compression, false)
	l += 6 // TimeSigned
	l += 2 // Fudge
	l += 2 // MACSize
	l += rr.MAC.EncodedLen()
	l += 2 // OrigId
	l += 2 // Error
	l += 2 // OtherLen
	l += rr.OtherData.EncodedLen()
	return l
}

func (rr *TXT) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += rr.Txt.EncodedLen()
	return l
}

func (rr *UID) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += 4 // Uid
	return l
}

func (rr *UINFO) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += rr.Uinfo.EncodedLen()
	return l
}

func (rr *URI) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += 2 // Priority
	l += 2 // Weight
	l += escapedNameLen(rr.Target)
	return l
}

func (rr *X25) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += rr.PSDNAddress.EncodedLen()
	return l
}

func (rr *ZONEMD) len(off int, compression map[Name]struct{}) int {
	l := rr.Hdr.len(off, compression)
	l += 4 // Serial
	l++    // Scheme
	l++    // Hash
	l += rr.Digest.EncodedLen()
	return l
}

// copy() functions
func (rr *A) copy() RR {
	return &A{rr.Hdr, rr.A}
}

func (rr *AAAA) copy() RR {
	return &AAAA{rr.Hdr, rr.AAAA}
}

func (rr *AFSDB) copy() RR {
	return &AFSDB{rr.Hdr, rr.Subtype, rr.Hostname}
}

func (rr *AMTRELAY) copy() RR {
	return &AMTRELAY{
		rr.Hdr,
		rr.Precedence,
		rr.GatewayType,
		rr.GatewayAddr,
		rr.GatewayHost,
	}
}

func (rr *ANY) copy() RR {
	return &ANY{rr.Hdr}
}

func (rr *APL) copy() RR {
	Prefixes := make([]APLPrefix, len(rr.Prefixes))
	for i, e := range rr.Prefixes {
		Prefixes[i] = e.copy()
	}
	return &APL{rr.Hdr, Prefixes}
}

func (rr *AVC) copy() RR {
	return &AVC{rr.Hdr, rr.Txt}
}

func (rr *CAA) copy() RR {
	return &CAA{
		rr.Hdr,
		rr.Flag,
		rr.Tag,
		rr.Value,
	}
}

func (rr *CDNSKEY) copy() RR {
	return &CDNSKEY{*rr.DNSKEY.copy().(*DNSKEY)}
}

func (rr *CDS) copy() RR {
	return &CDS{*rr.DS.copy().(*DS)}
}

func (rr *CERT) copy() RR {
	return &CERT{
		rr.Hdr,
		rr.Type,
		rr.KeyTag,
		rr.Algorithm,
		rr.Certificate,
	}
}

func (rr *CNAME) copy() RR {
	return &CNAME{rr.Hdr, rr.Target}
}

func (rr *CSYNC) copy() RR {
	return &CSYNC{
		rr.Hdr,
		rr.Serial,
		rr.Flags,
		slices.Clone(rr.TypeBitMap),
	}
}

func (rr *DHCID) copy() RR {
	return &DHCID{rr.Hdr, rr.Digest}
}

func (rr *DLV) copy() RR {
	return &DLV{*rr.DS.copy().(*DS)}
}

func (rr *DNAME) copy() RR {
	return &DNAME{rr.Hdr, rr.Target}
}

func (rr *DNSKEY) copy() RR {
	return &DNSKEY{
		rr.Hdr,
		rr.Flags,
		rr.Protocol,
		rr.Algorithm,
		rr.PublicKey,
	}
}

func (rr *DS) copy() RR {
	return &DS{
		rr.Hdr,
		rr.KeyTag,
		rr.Algorithm,
		rr.DigestType,
		rr.Digest,
	}
}

func (rr *EID) copy() RR {
	return &EID{rr.Hdr, rr.Endpoint}
}

func (rr *EUI48) copy() RR {
	return &EUI48{rr.Hdr, rr.Address}
}

func (rr *EUI64) copy() RR {
	return &EUI64{rr.Hdr, rr.Address}
}

func (rr *GID) copy() RR {
	return &GID{rr.Hdr, rr.Gid}
}

func (rr *GPOS) copy() RR {
	return &GPOS{
		rr.Hdr,
		rr.Longitude,
		rr.Latitude,
		rr.Altitude,
	}
}

func (rr *HINFO) copy() RR {
	return &HINFO{rr.Hdr, rr.Cpu, rr.Os}
}

func (rr *HIP) copy() RR {
	return &HIP{
		rr.Hdr,
		rr.HitLength,
		rr.PublicKeyAlgorithm,
		rr.PublicKeyLength,
		rr.Hit,
		rr.PublicKey,
		slices.Clone(rr.RendezvousServers),
	}
}

func (rr *HTTPS) copy() RR {
	return &HTTPS{*rr.SVCB.copy().(*SVCB)}
}

func (rr *IPSECKEY) copy() RR {
	return &IPSECKEY{
		rr.Hdr,
		rr.Precedence,
		rr.GatewayType,
		rr.Algorithm,
		rr.GatewayAddr,
		rr.GatewayHost,
		rr.PublicKey,
	}
}

func (rr *ISDN) copy() RR {
	return &ISDN{rr.Hdr, rr.Address, rr.SubAddress}
}

func (rr *KEY) copy() RR {
	return &KEY{*rr.DNSKEY.copy().(*DNSKEY)}
}

func (rr *KX) copy() RR {
	return &KX{rr.Hdr, rr.Preference, rr.Exchanger}
}

func (rr *L32) copy() RR {
	return &L32{rr.Hdr, rr.Preference, rr.Locator32}
}

func (rr *L64) copy() RR {
	return &L64{rr.Hdr, rr.Preference, rr.Locator64}
}

func (rr *LOC) copy() RR {
	return &LOC{
		rr.Hdr,
		rr.Version,
		rr.Size,
		rr.HorizPre,
		rr.VertPre,
		rr.Latitude,
		rr.Longitude,
		rr.Altitude,
	}
}

func (rr *LP) copy() RR {
	return &LP{rr.Hdr, rr.Preference, rr.Fqdn}
}

func (rr *MB) copy() RR {
	return &MB{rr.Hdr, rr.Mb}
}

func (rr *MD) copy() RR {
	return &MD{rr.Hdr, rr.Md}
}

func (rr *MF) copy() RR {
	return &MF{rr.Hdr, rr.Mf}
}

func (rr *MG) copy() RR {
	return &MG{rr.Hdr, rr.Mg}
}

func (rr *MINFO) copy() RR {
	return &MINFO{rr.Hdr, rr.Rmail, rr.Email}
}

func (rr *MR) copy() RR {
	return &MR{rr.Hdr, rr.Mr}
}

func (rr *MX) copy() RR {
	return &MX{rr.Hdr, rr.Preference, rr.Mx}
}

func (rr *NAPTR) copy() RR {
	return &NAPTR{
		rr.Hdr,
		rr.Order,
		rr.Preference,
		rr.Flags,
		rr.Service,
		rr.Regexp,
		rr.Replacement,
	}
}

func (rr *NID) copy() RR {
	return &NID{rr.Hdr, rr.Preference, rr.NodeID}
}

func (rr *NIMLOC) copy() RR {
	return &NIMLOC{rr.Hdr, rr.Locator}
}

func (rr *NINFO) copy() RR {
	return &NINFO{rr.Hdr, rr.ZSData}
}

func (rr *NS) copy() RR {
	return &NS{rr.Hdr, rr.Ns}
}

func (rr *NSAPPTR) copy() RR {
	return &NSAPPTR{rr.Hdr, rr.Ptr}
}

func (rr *NSEC) copy() RR {
	return &NSEC{rr.Hdr, rr.NextDomain, slices.Clone(rr.TypeBitMap)}
}

func (rr *NSEC3) copy() RR {
	return &NSEC3{
		rr.Hdr,
		rr.Hash,
		rr.Flags,
		rr.Iterations,
		rr.SaltLength,
		rr.Salt,
		rr.HashLength,
		rr.NextDomain,
		slices.Clone(rr.TypeBitMap),
	}
}

func (rr *NSEC3PARAM) copy() RR {
	return &NSEC3PARAM{
		rr.Hdr,
		rr.Hash,
		rr.Flags,
		rr.Iterations,
		rr.SaltLength,
		rr.Salt,
	}
}

func (rr *NULL) copy() RR {
	return &NULL{rr.Hdr, rr.Data}
}

func (rr *NXNAME) copy() RR {
	return &NXNAME{rr.Hdr}
}

func (rr *NXT) copy() RR {
	return &NXT{*rr.NSEC.copy().(*NSEC)}
}

func (rr *OPENPGPKEY) copy() RR {
	return &OPENPGPKEY{rr.Hdr, rr.PublicKey}
}

func (rr *OPT) copy() RR {
	Option := make([]EDNS0, len(rr.Option))
	for i, e := range rr.Option {
		Option[i] = e.copy()
	}
	return &OPT{rr.Hdr, Option}
}

func (rr *PTR) copy() RR {
	return &PTR{rr.Hdr, rr.Ptr}
}

func (rr *PX) copy() RR {
	return &PX{
		rr.Hdr,
		rr.Preference,
		rr.Map822,
		rr.Mapx400,
	}
}

func (rr *RESINFO) copy() RR {
	return &RESINFO{rr.Hdr, rr.Txt}
}

func (rr *RFC3597) copy() RR {
	return &RFC3597{rr.Hdr, rr.Rdata}
}

func (rr *RKEY) copy() RR {
	return &RKEY{
		rr.Hdr,
		rr.Flags,
		rr.Protocol,
		rr.Algorithm,
		rr.PublicKey,
	}
}

func (rr *RP) copy() RR {
	return &RP{rr.Hdr, rr.Mbox, rr.Txt}
}

func (rr *RRSIG) copy() RR {
	return &RRSIG{
		rr.Hdr,
		rr.TypeCovered,
		rr.Algorithm,
		rr.Labels,
		rr.OrigTtl,
		rr.Expiration,
		rr.Inception,
		rr.KeyTag,
		rr.SignerName,
		rr.Signature,
	}
}

func (rr *RT) copy() RR {
	return &RT{rr.Hdr, rr.Preference, rr.Host}
}

func (rr *SIG) copy() RR {
	return &SIG{*rr.RRSIG.copy().(*RRSIG)}
}

func (rr *SMIMEA) copy() RR {
	return &SMIMEA{
		rr.Hdr,
		rr.Usage,
		rr.Selector,
		rr.MatchingType,
		rr.Certificate,
	}
}

func (rr *SOA) copy() RR {
	return &SOA{
		rr.Hdr,
		rr.Ns,
		rr.Mbox,
		rr.Serial,
		rr.Refresh,
		rr.Retry,
		rr.Expire,
		rr.Minttl,
	}
}

func (rr *SPF) copy() RR {
	return &SPF{rr.Hdr, rr.Txt}
}

func (rr *SRV) copy() RR {
	return &SRV{
		rr.Hdr,
		rr.Priority,
		rr.Weight,
		rr.Port,
		rr.Target,
	}
}

func (rr *SSHFP) copy() RR {
	return &SSHFP{
		rr.Hdr,
		rr.Algorithm,
		rr.Type,
		rr.FingerPrint,
	}
}

func (rr *SVCB) copy() RR {
	Value := make([]SVCBKeyValue, len(rr.Value))
	for i, e := range rr.Value {
		Value[i] = e.copy()
	}
	return &SVCB{
		rr.Hdr,
		rr.Priority,
		rr.Target,
		Value,
	}
}

func (rr *TA) copy() RR {
	return &TA{
		rr.Hdr,
		rr.KeyTag,
		rr.Algorithm,
		rr.DigestType,
		rr.Digest,
	}
}

func (rr *TALINK) copy() RR {
	return &TALINK{rr.Hdr, rr.PreviousName, rr.NextName}
}

func (rr *TKEY) copy() RR {
	return &TKEY{
		rr.Hdr,
		rr.Algorithm,
		rr.Inception,
		rr.Expiration,
		rr.Mode,
		rr.Error,
		rr.KeySize,
		rr.Key,
		rr.OtherLen,
		rr.OtherData,
	}
}

func (rr *TLSA) copy() RR {
	return &TLSA{
		rr.Hdr,
		rr.Usage,
		rr.Selector,
		rr.MatchingType,
		rr.Certificate,
	}
}

func (rr *TSIG) copy() RR {
	return &TSIG{
		rr.Hdr,
		rr.Algorithm,
		rr.TimeSigned,
		rr.Fudge,
		rr.MACSize,
		rr.MAC,
		rr.OrigId,
		rr.Error,
		rr.OtherLen,
		rr.OtherData,
	}
}

func (rr *TXT) copy() RR {
	return &TXT{rr.Hdr, rr.Txt}
}

func (rr *UID) copy() RR {
	return &UID{rr.Hdr, rr.Uid}
}

func (rr *UINFO) copy() RR {
	return &UINFO{rr.Hdr, rr.Uinfo}
}

func (rr *URI) copy() RR {
	return &URI{
		rr.Hdr,
		rr.Priority,
		rr.Weight,
		rr.Target,
	}
}

func (rr *X25) copy() RR {
	return &X25{rr.Hdr, rr.PSDNAddress}
}

func (rr *ZONEMD) copy() RR {
	return &ZONEMD{
		rr.Hdr,
		rr.Serial,
		rr.Scheme,
		rr.Hash,
		rr.Digest,
	}
}

// String() functions
func (rr *A) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	if rr.A.IsValid() {
		b.WriteString(rr.A.String())
	}

	return b.String()
}

func (rr *AAAA) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	if rr.AAAA.IsValid() {
		b.WriteString(rr.AAAA.String())
	}

	return b.String()
}

func (rr *AFSDB) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(strconv.FormatInt(int64(rr.Subtype), 10))
	b.WriteByte(' ')
	b.WriteString(rr.Hostname.String())
	return b.String()
}

func (rr *ANY) String() string {
	return rr.Hdr.String()
}

func (rr *APL) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	for i, p := range rr.Prefixes {
		if i > 0 {
			b.WriteByte(' ')
		}
		b.WriteString(p.str())
	}
	return b.String()
}

func (rr *AVC) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.Txt.String())
	return b.String()
}

func (rr *CAA) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(strconv.FormatInt(int64(rr.Flag), 10))
	b.WriteByte(' ')
	b.WriteString(rr.Tag.BareString())
	b.WriteByte(' ')
	b.WriteString(sprintTxtOctet(rr.Value))
	return b.String()
}

func (rr *CNAME) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.Target.String())
	return b.String()
}

func (rr *CSYNC) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(strconv.FormatInt(int64(rr.Serial), 10))
	b.WriteByte(' ')
	b.WriteString(strconv.FormatInt(int64(rr.Flags), 10))
	for _, t := range rr.TypeBitMap {
		b.WriteByte(' ')
		b.WriteString(Type(t).String())
	}
	return b.String()
}

func (rr *DHCID) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.Digest.Base64())
	return b.String()
}

func (rr *DNAME) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.Target.String())
	return b.String()
}

func (rr *DNSKEY) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(strconv.FormatInt(int64(rr.Flags), 10))
	b.WriteByte(' ')
	b.WriteString(strconv.FormatInt(int64(rr.Protocol), 10))
	b.WriteByte(' ')
	b.WriteString(strconv.FormatInt(int64(rr.Algorithm), 10))
	b.WriteByte(' ')
	b.WriteString(rr.PublicKey.Base64())
	return b.String()
}

func (rr *DS) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(strconv.FormatInt(int64(rr.KeyTag), 10))
	b.WriteByte(' ')
	b.WriteString(strconv.FormatInt(int64(rr.Algorithm), 10))
	b.WriteByte(' ')
	b.WriteString(strconv.FormatInt(int64(rr.DigestType), 10))
	b.WriteByte(' ')
	b.WriteString(rr.Digest.Hex())
	return b.String()
}

func (rr *EID) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.Endpoint.Hex())
	return b.String()
}

func (rr *EUI48) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(euiToString(rr.Address, 48))
	return b.String()
}

func (rr *EUI64) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(euiToString(rr.Address, 64))
	return b.String()
}

func (rr *GID) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(strconv.FormatInt(int64(rr.Gid), 10))
	return b.String()
}

func (rr *GPOS) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.Longitude.BareString())
	b.WriteByte(' ')
	b.WriteString(rr.Latitude.BareString())
	b.WriteByte(' ')
	b.WriteString(rr.Altitude.BareString())
	return b.String()
}

func (rr *HINFO) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.Cpu.String())
	b.WriteByte(' ')
	b.WriteString(rr.Os.String())
	return b.String()
}

func (rr *ISDN) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.Address.String())
	b.WriteByte(' ')
	b.WriteString(rr.SubAddress.String())
	return b.String()
}

func (rr *KX) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(strconv.FormatInt(int64(rr.Preference), 10))
	b.WriteByte(' ')
	b.WriteString(rr.Exchanger.String())
	return b.String()
}

func (rr *L32) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(strconv.FormatInt(int64(rr.Preference), 10))
	if rr.Locator32.IsValid() {
		b.WriteByte(' ')
		b.WriteString(rr.Locator32.String())
	}

	return b.String()
}

func (rr *LP) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(strconv.FormatInt(int64(rr.Preference), 10))
	b.WriteByte(' ')
	b.WriteString(rr.Fqdn.String())
	return b.String()
}

func (rr *MB) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.Mb.String())
	return b.String()
}

func (rr *MD) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.Md.String())
	return b.String()
}

func (rr *MF) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.Mf.String())
	return b.String()
}

func (rr *MG) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.Mg.String())
	return b.String()
}

func (rr *MINFO) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.Rmail.String())
	b.WriteByte(' ')
	b.WriteString(rr.Email.String())
	return b.String()
}

func (rr *MR) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.Mr.String())
	return b.String()
}

func (rr *MX) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(strconv.FormatInt(int64(rr.Preference), 10))
	b.WriteByte(' ')
	b.WriteString(rr.Mx.String())
	return b.String()
}

func (rr *NIMLOC) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.Locator.Hex())
	return b.String()
}

func (rr *NINFO) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.ZSData.String())
	return b.String()
}

func (rr *NS) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.Ns.String())
	return b.String()
}

func (rr *NSAPPTR) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.Ptr.String())
	return b.String()
}

func (rr *NSEC) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.NextDomain.String())
	for _, t := range rr.TypeBitMap {
		b.WriteByte(' ')
		b.WriteString(Type(t).String())
	}
	return b.String()
}

func (rr *NULL) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.Data.Hex())
	return b.String()
}

func (rr *NXNAME) String() string {
	return rr.Hdr.String()
}

func (rr *OPENPGPKEY) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.PublicKey.Base64())
	return b.String()
}

func (rr *PTR) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.Ptr.String())
	return b.String()
}

func (rr *PX) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(strconv.FormatInt(int64(rr.Preference), 10))
	b.WriteByte(' ')
	b.WriteString(rr.Map822.String())
	b.WriteByte(' ')
	b.WriteString(rr.Mapx400.String())
	return b.String()
}

func (rr *RESINFO) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.Txt.String())
	return b.String()
}

func (rr *RKEY) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(strconv.FormatInt(int64(rr.Flags), 10))
	b.WriteByte(' ')
	b.WriteString(strconv.FormatInt(int64(rr.Protocol), 10))
	b.WriteByte(' ')
	b.WriteString(strconv.FormatInt(int64(rr.Algorithm), 10))
	b.WriteByte(' ')
	b.WriteString(rr.PublicKey.Base64())
	return b.String()
}

func (rr *RP) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.Mbox.String())
	b.WriteByte(' ')
	b.WriteString(rr.Txt.String())
	return b.String()
}

func (rr *RRSIG) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.TypeCovered.String())
	b.WriteByte(' ')
	b.WriteString(strconv.FormatInt(int64(rr.Algorithm), 10))
	b.WriteByte(' ')
	b.WriteString(strconv.FormatInt(int64(rr.Labels), 10))
	b.WriteByte(' ')
	b.WriteString(strconv.FormatInt(int64(rr.OrigTtl), 10))
	b.WriteByte(' ')
	b.WriteString(rr.Expiration.String())
	b.WriteByte(' ')
	b.WriteString(rr.Inception.String())
	b.WriteByte(' ')
	b.WriteString(strconv.FormatInt(int64(rr.KeyTag), 10))
	b.WriteByte(' ')
	b.WriteString(rr.SignerName.String())
	b.WriteByte(' ')
	b.WriteString(rr.Signature.Base64())
	return b.String()
}

func (rr *RT) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(strconv.FormatInt(int64(rr.Preference), 10))
	b.WriteByte(' ')
	b.WriteString(rr.Host.String())
	return b.String()
}

func (rr *SOA) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.Ns.String())
	b.WriteByte(' ')
	b.WriteString(rr.Mbox.String())
	b.WriteByte(' ')
	b.WriteString(strconv.FormatInt(int64(rr.Serial), 10))
	b.WriteByte(' ')
	b.WriteString(strconv.FormatInt(int64(rr.Refresh), 10))
	b.WriteByte(' ')
	b.WriteString(strconv.FormatInt(int64(rr.Retry), 10))
	b.WriteByte(' ')
	b.WriteString(strconv.FormatInt(int64(rr.Expire), 10))
	b.WriteByte(' ')
	b.WriteString(strconv.FormatInt(int64(rr.Minttl), 10))
	return b.String()
}

func (rr *SPF) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.Txt.String())
	return b.String()
}

func (rr *SRV) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(strconv.FormatInt(int64(rr.Priority), 10))
	b.WriteByte(' ')
	b.WriteString(strconv.FormatInt(int64(rr.Weight), 10))
	b.WriteByte(' ')
	b.WriteString(strconv.FormatInt(int64(rr.Port), 10))
	b.WriteByte(' ')
	b.WriteString(rr.Target.String())
	return b.String()
}

func (rr *SSHFP) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(strconv.FormatInt(int64(rr.Algorithm), 10))
	b.WriteByte(' ')
	b.WriteString(strconv.FormatInt(int64(rr.Type), 10))
	b.WriteByte(' ')
	b.WriteString(rr.FingerPrint.Hex())
	return b.String()
}

func (rr *SVCB) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(strconv.FormatInt(int64(rr.Priority), 10))
	b.WriteByte(' ')
	b.WriteString(rr.Target.String())
	for _, e := range rr.Value {
		b.WriteByte(' ')
		b.WriteString(e.Key().String())
		b.WriteString("=\"")
		b.WriteString(e.String())
		b.WriteByte('"')
	}
	return b.String()
}

func (rr *TA) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(strconv.FormatInt(int64(rr.KeyTag), 10))
	b.WriteByte(' ')
	b.WriteString(strconv.FormatInt(int64(rr.Algorithm), 10))
	b.WriteByte(' ')
	b.WriteString(strconv.FormatInt(int64(rr.DigestType), 10))
	b.WriteByte(' ')
	b.WriteString(rr.Digest.Hex())
	return b.String()
}

func (rr *TALINK) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.PreviousName.String())
	b.WriteByte(' ')
	b.WriteString(rr.NextName.String())
	return b.String()
}

func (rr *TLSA) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(strconv.FormatInt(int64(rr.Usage), 10))
	b.WriteByte(' ')
	b.WriteString(strconv.FormatInt(int64(rr.Selector), 10))
	b.WriteByte(' ')
	b.WriteString(strconv.FormatInt(int64(rr.MatchingType), 10))
	b.WriteByte(' ')
	b.WriteString(rr.Certificate.Hex())
	return b.String()
}

func (rr *TXT) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.Txt.String())
	return b.String()
}

func (rr *UID) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(strconv.FormatInt(int64(rr.Uid), 10))
	return b.String()
}

func (rr *UINFO) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.Uinfo.String())
	return b.String()
}

func (rr *URI) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(strconv.FormatInt(int64(rr.Priority), 10))
	b.WriteByte(' ')
	b.WriteString(strconv.FormatInt(int64(rr.Weight), 10))
	b.WriteByte(' ')
	b.WriteString(sprintTxtOctet(rr.Target))
	return b.String()
}

func (rr *X25) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(rr.PSDNAddress.BareString())
	return b.String()
}

func (rr *ZONEMD) String() string {
	var b strings.Builder
	b.WriteString(rr.Hdr.String())
	b.WriteString(strconv.FormatInt(int64(rr.Serial), 10))
	b.WriteByte(' ')
	b.WriteString(strconv.FormatInt(int64(rr.Scheme), 10))
	b.WriteByte(' ')
	b.WriteString(strconv.FormatInt(int64(rr.Hash), 10))
	b.WriteByte(' ')
	b.WriteString(rr.Digest.Hex())
	return b.String()
}
